# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c442e272363904e15cf84941e2f1be22ad47910a395b66c70d03576ca550373722cccf801b868d667c5fbee87d786553a8d47799b80dca4e647ac5c7443b0e83

test:
  secret_key_base: 2f20d31f04ab05119ffe5ee29fca8c98247f5485e37f8f1d2c130d031589ff40d93442a09236837bf099707fb17dc70acffb67e633abad03739cdcb706fe7645

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
